markdown: rdiscount
permalink: /:year/:month/:title/
name: Yet Another Programmer`s Blog
url: http://greycode.github.io/
author: "greycode"
highlighter: false
paginate: 24
excerpt_separator: <!--more-->
gems: 
    - jekyll-paginate
